language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - android-27
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-27
    - extra-android-m2repository